#!/usr/bin/env php
<?php

declare(strict_types=1);

$backendArtisan = __DIR__ . '/backend/artisan';

if (!is_file($backendArtisan)) {
    fwrite(STDERR, "Missing backend/artisan\n");
    exit(1);
}

$args = array_slice($argv, 1);
$command = escapeshellarg(PHP_BINARY) . ' ' . escapeshellarg($backendArtisan);

foreach ($args as $arg) {
    $command .= ' ' . escapeshellarg($arg);
}

passthru($command, $status);
exit($status);
